---
openapi: 3.0.3

#servers:
#- url: /api

info:
  title: Librerian
  description: |-
    
    [Librerian repository](https://github.com/moiz-naeem/WEB-API)
#  termsOfService: http://foobar.placeholder
#  contact:
#    email: foobar@email.com
  license:
    name: GPL-3.0
    url: https://www.gnu.org/licenses/gpl-3.0.en.html
  version: 0.0.1

tags:
 -  name: User
    description: Everything about users
 -  name: Library
    description: Everything about libraries
 -  name: Book
    description: Everything about books
 -  name: Work
    description: Everything about works

components:
  schemas:
    User:
      type: object
      required:
      - handle
      - email
      properties:
        contact_phone:
          description: Phone number of the user
          maxLength: 64
          minLength: 1
          type: string
        email:
          description: Email address of the user
          format: idn-email
          maxLength: 64
          minLength: 1
          type: string
        first_name:
          description: First name of the user
          maxLength: 64
          minLength: 1
          type: string
        handle:
          description: Handle of the user (must be unique for each user)
          maxLength: 64
          minLength: 1
          type: string
        last_name:
          description: Last name of the user
          maxLength: 64
          minLength: 1
          type: string
    Library:
      type: object
      required:
      - name
      properties:
        address_line_1:
          description: ''
          maxLength: 64
          minLength: 1
          type: string
        address_line_2:
          description: ''
          maxLength: 64
          minLength: 1
          type: string
        city:
          description: ''
          maxLength: 64
          minLength: 1
          type: string
        contact_email:
          description: ''
          format: idn-email
          maxLength: 64
          minLength: 1
          type: string
        country:
          description: ''
          maxLength: 2
          minLength: 2
          type: string
        name:
          description: Name of the library
          maxLength: 64
          minLength: 1
          type: string
        postal_code:
          description: ''
          maxLength: 64
          minLength: 1
          type: string
    Book:
      type: object
      required:
      - status
      - work_id
      properties:
        condition:
          description: ''
          maxLength: 64
          minLength: 1
          type: string
        notes:
          description: User defined notes for the book
          maxLength: 64
          minLength: 1
          type: string
        status:
          description: Status code of the book, range from (0-N)
          enum:
          - 0
          - 1
          - 2
          - 3
          - 4
          - 5
          type: integer
        validity_end:
          description: Datetime for when the book is due to be returned
          format: date-time
          type: string
        validity_start:
          description: Datetime for when the book was borrowed
          format: date-time
          type: string
        work_id:
          description: ID of the work that the book is an instance of
          type: integer
    Work:
      type: object
      required:
      - title
      - author
      properties:
        author:
          description: Name of the work's author
          maxLength: 64
          minLength: 1
          type: string
        cover:
          description: URI pointing to the cover of the work
          format: uri
          maxLength: 64
          minLength: 1
          type: string
        isbn:
          description: ISBN of the work
          maxLength: 64
          minLength: 1
          type: string
        title:
          description: Title of the work
          maxLength: 64
          minLength: 1
          type: string

  parameters:
    userParam:
      name: user
      in: path
      description: User handle
      required: true
      schema:
        type: string
    libraryParam:
      name: library
      in: path
      description: Library name
      required: true
      schema:
        type: string
    bookParam:
      name: book
      in: path
      description: Book id
      required: true
      schema:
        type: integer
    workParam:
      name: work
      in: path
      description: Work id
      required: true
      schema:
        type: integer